name: auth-cas_devcontainer
services:
  keycloak:
    build: ./keycloak
    image: keycloak:cas
    environment:
      # https://www.keycloak.org/server/configuration
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN:-admin}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD:-admin}
      # https://www.keycloak.org/server/reverseproxy
      KC_PROXY_HEADERS: xforwarded
    volumes:
      - keycloak_data:/opt/keycloak/data
      - ${LOCAL_WORKSPACE_FOLDER:-.}/.devcontainer/keycloak/export:/opt/keycloak/data/export
      - ${LOCAL_WORKSPACE_FOLDER:-.}/.devcontainer/keycloak/import:/opt/keycloak/data/import
    command: start-dev --import-realm
    ports:
      - 127.0.0.1:8080:8080

  redis:
    # https://hub.docker.com/_/redis
    image: redis
    restart: unless-stopped
    volumes:
      - redis_data:/data
    ports:
      - 127.0.0.1:6379:6379

volumes:
    keycloak_data:
    redis_data: