version: '2'
name: auth-cas_devcontainer
services:
  dotnet:
    # https://github.com/devcontainers/images/blob/main/src/dotnet
    build: .
    image: dotnet-sdk:mono
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      PATH: $PATH:/home/vscode/.dotnet:/home/vscode/.dotnet/tools
    volumes:
      - ..:/workspaces:cached
      # https://learn.microsoft.com/aspnet/core/security/docker-compose-https
      - ~/.aspnet/https:/home/vscode/.aspnet/https:ro
    command: sleep infinity

  keycloak:
    build: 
      context: ./keycloak
    image: keycloak:cas
    environment:
      # https://www.keycloak.org/server/configuration
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN:-admin}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD:-admin}
      # https://www.keycloak.org/server/all-config
      KC_HOSTNAME: auth.dev.local
      KC_HTTP_ENABLED: 'true'
      KC_HTTPS_PORT: 443
      KC_HTTPS_CERTIFICATE_FILE: /opt/keycloak/certs/cert.pem
      KC_HTTPS_CERTIFICATE_KEY_FILE: /opt/keycloak/certs/key.pem
    volumes:
      - keycloak-data:/opt/keycloak/data
      - ./certs:/opt/keycloak/certs
      - ./keycloak/export:/opt/keycloak/data/export
      - ./keycloak/import:/opt/keycloak/data/import
    command: start --optimized --import-realm
    ports:
      - 127.0.0.1:8080:8080
      - 127.0.0.1:443:443

volumes:
    keycloak-data: