name: Build OWIN sample

on:
  push:
    paths:
      - 'samples/OwinSample/**'
  pull_request:
    paths:
      - 'samples/OwinSample/**'

permissions: read-all

jobs:
  msbuild:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up MSBuild
        uses: microsoft/setup-msbuild@v2
        with:
          msbuild-architecture: x64
      - name: Build
        run: |
          msbuild -version
          msbuild samples/OwinSample/OwinSample.csproj -noLogo -verbosity:minimal -restore
